### ISSUE TITLE
TypeError: responder.scrollResponderScrollTo is not a function.

### ISSUE THREAD

**Issue by nikhil-kumar-160** [codler/react-native-keyboard-aware-scroll-view#14]
This issue is resolved in the new 'APSL/react-native-keyboard-aware-scroll-view' but not in this repository.

Please make the required changes in KeyboardAwareHOC.js file

![code](https://user-images.githubusercontent.com/89442532/145531229-eb6dd1df-b6c9-4d4f-8cbe-88ab3166f74b.png)

**Comment by codler** [comment]
@nikhil-kumar-160 What react native version are you using?

**Comment by nikhil-kumar-160** [comment]
React native 0.66.4

**Comment by codler** [comment]
Fixed in v2.0.1
