### ISSUE TITLE
Unexpected token - react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js 13:12

### ISSUE THREAD

**Issue by lewisjones28** [codler/react-native-keyboard-aware-scroll-view#7]
Module parse failed: Unexpected token (15:33)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { isIphoneX } from 'react-native-iphone-x-helper'

> const _KAM_DEFAULT_TAB_BAR_HEIGHT: number = isIphoneX() ? 83 : 49
const _KAM_KEYBOARD_OPENING_TIME: number = 250
const _KAM_EXTRA_HEIGHT: number = 75

**Comment by GilTorch** [comment]
Did you solve this?

**Comment by matias91** [comment]
Hi!

The solution from this issue worked for me: https://github.com/codler/react-native-keyboard-aware-scroll-view/issues/4
This works too: https://forums.expo.io/t/expo-start-web-failed-to-compile-after-import-native-base/40826/9?u=matias.calvo

**Comment by rabidkitten** [comment]
I tried @matias91 what you suggested under the forum above, but I just get another error. It works on a mobile device fine, but not on the web. The other solution seems to be rolling back native base to an earlier version? This doesn't seem to be a solution though...
