### ISSUE TITLE
currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput

### ISSUE THREAD

**Issue by patricktan98** [codler/react-native-keyboard-aware-scroll-view#8]
In below environment:
react-native-keyboard-aware-scroll-view:1.0.1
react-native:0.63.3
native-base:2.15.1

The warning still persisted although version 1.0.1 was rolled out.
![image](https://user-images.githubusercontent.com/50147719/106179273-c373b300-61d5-11eb-9b88-f3d2ffd91c36.png)

**Comment by arunpugahz** [comment]
Facing same issue
